# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Require NodeJS version 14 and up
        node-version: [14.x, 16.x]
        os:
          [ubuntu-latest, windows-latest, macos-latest, macos-12, windows-2019]
        arch: [x64, x86, arm64, armv6l, armv7l, ppc64le, s390x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # Testing with different arch
          architecture: ${{ matrix.arch }}
          # Cache dependencies
          cache: "yarn"
          # path: "client"
      - name: "Installing dependencies"
        run: yarn install --frozen-lockfile
        # working-directory: "client"

      - name: "Running test cases"
        run: yarn test
        # working-directory: "client"
